//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region AssetComment
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetComment :
        global::LightSwitchApplication.AssetComment.DetailsClass.IImplementation
    {
        partial void OnAssetComment_AssetChanged()
        {
            this.___OnPropertyChanged("AssetComment_Asset");
            this.___OnPropertyChanged("Asset");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCommentDateChanged()
        {
            this.___OnPropertyChanged("CommentDate");
        }
        
        partial void OnCommentChanged()
        {
            this.___OnPropertyChanged("Comment");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetComment.DetailsClass.IImplementation.Asset
        {
            get
            {
                return this.Asset;
            }
            set
            {
                this.Asset = (global::LightSwitchApplication.Implementation.Asset)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> __Asset
        {
            get
            {
                if (this.___Asset == null)
                {
                    this.___Asset = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Asset",
                        new string[] { "AssetComment_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetComment_Asset),
                        () => this._Asset,
                        e => this._Asset = e);
                }
                return this.___Asset;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> ___Asset;
        
    }
    #endregion
    
    #region AssetMaintenanceActivity
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetMaintenanceActivity :
        global::LightSwitchApplication.AssetMaintenanceActivity.DetailsClass.IImplementation
    {
        partial void OnAssetMaintenanceActivity_AssetChanged()
        {
            this.___OnPropertyChanged("AssetMaintenanceActivity_Asset");
            this.___OnPropertyChanged("Asset");
        }
        
        partial void OnAssetMaintenanceActivity_AssetMaintenanceTypeChanged()
        {
            this.___OnPropertyChanged("AssetMaintenanceActivity_AssetMaintenanceType");
            this.___OnPropertyChanged("AssetMaintenanceType");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateDueChanged()
        {
            this.___OnPropertyChanged("DateDue");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnOutcomeChanged()
        {
            this.___OnPropertyChanged("Outcome");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetMaintenanceActivity.DetailsClass.IImplementation.Asset
        {
            get
            {
                return this.Asset;
            }
            set
            {
                this.Asset = (global::LightSwitchApplication.Implementation.Asset)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> __Asset
        {
            get
            {
                if (this.___Asset == null)
                {
                    this.___Asset = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Asset",
                        new string[] { "AssetMaintenanceActivity_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetMaintenanceActivity_Asset),
                        () => this._Asset,
                        e => this._Asset = e);
                }
                return this.___Asset;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> ___Asset;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetMaintenanceActivity.DetailsClass.IImplementation.AssetMaintenanceType
        {
            get
            {
                return this.AssetMaintenanceType;
            }
            set
            {
                this.AssetMaintenanceType = (global::LightSwitchApplication.Implementation.AssetMaintenanceType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetMaintenanceType> __AssetMaintenanceType
        {
            get
            {
                if (this.___AssetMaintenanceType == null)
                {
                    this.___AssetMaintenanceType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetMaintenanceType>(
                        this,
                        "AssetMaintenanceType",
                        new string[] { "AssetMaintenanceActivity_AssetMaintenanceType" },
                        e => global::System.Object.Equals(e.Id, this.AssetMaintenanceActivity_AssetMaintenanceType),
                        () => this._AssetMaintenanceType,
                        e => this._AssetMaintenanceType = e);
                }
                return this.___AssetMaintenanceType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetMaintenanceType> ___AssetMaintenanceType;
        
    }
    #endregion
    
    #region AssetMaintenanceSchedule
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetMaintenanceSchedule :
        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.IImplementation
    {
        partial void OnAssetMaintenanceSchedule_AssetChanged()
        {
            this.___OnPropertyChanged("AssetMaintenanceSchedule_Asset");
            this.___OnPropertyChanged("Asset");
        }
        
        partial void OnAssetMaintenanceSchedule_AssetMaintenanceTypeChanged()
        {
            this.___OnPropertyChanged("AssetMaintenanceSchedule_AssetMaintenanceType");
            this.___OnPropertyChanged("AssetMaintenanceType");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnMaintenanceTypeIntervalInMonthsChanged()
        {
            this.___OnPropertyChanged("MaintenanceTypeIntervalInMonths");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.IImplementation.Asset
        {
            get
            {
                return this.Asset;
            }
            set
            {
                this.Asset = (global::LightSwitchApplication.Implementation.Asset)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> __Asset
        {
            get
            {
                if (this.___Asset == null)
                {
                    this.___Asset = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Asset",
                        new string[] { "AssetMaintenanceSchedule_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetMaintenanceSchedule_Asset),
                        () => this._Asset,
                        e => this._Asset = e);
                }
                return this.___Asset;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> ___Asset;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.IImplementation.AssetMaintenanceType
        {
            get
            {
                return this.AssetMaintenanceType;
            }
            set
            {
                this.AssetMaintenanceType = (global::LightSwitchApplication.Implementation.AssetMaintenanceType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetMaintenanceType> __AssetMaintenanceType
        {
            get
            {
                if (this.___AssetMaintenanceType == null)
                {
                    this.___AssetMaintenanceType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetMaintenanceType>(
                        this,
                        "AssetMaintenanceType",
                        new string[] { "AssetMaintenanceSchedule_AssetMaintenanceType" },
                        e => global::System.Object.Equals(e.Id, this.AssetMaintenanceSchedule_AssetMaintenanceType),
                        () => this._AssetMaintenanceType,
                        e => this._AssetMaintenanceType = e);
                }
                return this.___AssetMaintenanceType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetMaintenanceType> ___AssetMaintenanceType;
        
    }
    #endregion
    
    #region AssetMaintenanceType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetMaintenanceType :
        global::LightSwitchApplication.AssetMaintenanceType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnMaintenanceTypeDescriptionChanged()
        {
            this.___OnPropertyChanged("MaintenanceTypeDescription");
        }
        
        partial void OnInUseChanged()
        {
            this.___OnPropertyChanged("InUse");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AssetMaintenanceType.DetailsClass.IImplementation.AssetMaintenanceActivities
        {
            get
            {
                return this.AssetMaintenanceActivities;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceActivity> __AssetMaintenanceActivities
        {
            get
            {
                if (this.___AssetMaintenanceActivities == null)
                {
                    this.___AssetMaintenanceActivities = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceActivity>(
                        this,
                        "AssetMaintenanceActivities",
                        () => this._AssetMaintenanceActivities,
                        e => global::System.Object.Equals(e.AssetMaintenanceActivity_AssetMaintenanceType, this.Id));
                }
                return this.___AssetMaintenanceActivities;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceActivity> ___AssetMaintenanceActivities;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AssetMaintenanceType.DetailsClass.IImplementation.AssetMaintenanceSchedules
        {
            get
            {
                return this.AssetMaintenanceSchedules;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule> __AssetMaintenanceSchedules
        {
            get
            {
                if (this.___AssetMaintenanceSchedules == null)
                {
                    this.___AssetMaintenanceSchedules = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule>(
                        this,
                        "AssetMaintenanceSchedules",
                        () => this._AssetMaintenanceSchedules,
                        e => global::System.Object.Equals(e.AssetMaintenanceSchedule_AssetMaintenanceType, this.Id));
                }
                return this.___AssetMaintenanceSchedules;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule> ___AssetMaintenanceSchedules;
        
    }
    #endregion
    
    #region AssetManufacturer
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetManufacturer :
        global::LightSwitchApplication.AssetManufacturer.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnManufacturerChanged()
        {
            this.___OnPropertyChanged("Manufacturer");
        }
        
        partial void OnAddressLine1Changed()
        {
            this.___OnPropertyChanged("AddressLine1");
        }
        
        partial void OnAddressLine2Changed()
        {
            this.___OnPropertyChanged("AddressLine2");
        }
        
        partial void OnAddressLine3Changed()
        {
            this.___OnPropertyChanged("AddressLine3");
        }
        
        partial void OnAddressLine4Changed()
        {
            this.___OnPropertyChanged("AddressLine4");
        }
        
        partial void OnAddressLine5Changed()
        {
            this.___OnPropertyChanged("AddressLine5");
        }
        
        partial void OnPostCodeChanged()
        {
            this.___OnPropertyChanged("PostCode");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhone1Changed()
        {
            this.___OnPropertyChanged("Phone1");
        }
        
        partial void OnPhone2Changed()
        {
            this.___OnPropertyChanged("Phone2");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnWebsiteChanged()
        {
            this.___OnPropertyChanged("Website");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AssetManufacturer.DetailsClass.IImplementation.Assets
        {
            get
            {
                return this.Assets;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset> __Assets
        {
            get
            {
                if (this.___Assets == null)
                {
                    this.___Assets = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Assets",
                        () => this._Assets,
                        e => global::System.Object.Equals(e.AssetManufacturer_Asset, this.Id));
                }
                return this.___Assets;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset> ___Assets;
        
    }
    #endregion
    
    #region Asset
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Asset :
        global::LightSwitchApplication.Asset.DetailsClass.IImplementation
    {
        partial void OnAssetManufacturer_AssetChanged()
        {
            this.___OnPropertyChanged("AssetManufacturer_Asset");
            this.___OnPropertyChanged("AssetManufacturer");
        }
        
        partial void OnAssetSupplier_AssetChanged()
        {
            this.___OnPropertyChanged("AssetSupplier_Asset");
            this.___OnPropertyChanged("AssetSupplier");
        }
        
        partial void OnAssetType_AssetChanged()
        {
            this.___OnPropertyChanged("AssetType_Asset");
            this.___OnPropertyChanged("AssetType");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnReferenceChanged()
        {
            this.___OnPropertyChanged("Reference");
        }
        
        partial void OnAssetDescriptionChanged()
        {
            this.___OnPropertyChanged("AssetDescription");
        }
        
        partial void OnSerialNumberChanged()
        {
            this.___OnPropertyChanged("SerialNumber");
        }
        
        partial void OnModelChanged()
        {
            this.___OnPropertyChanged("Model");
        }
        
        partial void OnLocationChanged()
        {
            this.___OnPropertyChanged("Location");
        }
        
        partial void OnPurchaseDateChanged()
        {
            this.___OnPropertyChanged("PurchaseDate");
        }
        
        partial void OnCommissionDateChanged()
        {
            this.___OnPropertyChanged("CommissionDate");
        }
        
        partial void OnIntendedReplacementDateChanged()
        {
            this.___OnPropertyChanged("IntendedReplacementDate");
        }
        
        partial void OnInUseChanged()
        {
            this.___OnPropertyChanged("InUse");
        }
        
        partial void OnDateRemovedFromUseChanged()
        {
            this.___OnPropertyChanged("DateRemovedFromUse");
        }
        
        partial void OnAssetImageChanged()
        {
            this.___OnPropertyChanged("AssetImage");
        }
        
        partial void OnCapitalAssetReferenceChanged()
        {
            this.___OnPropertyChanged("CapitalAssetReference");
        }
        
        partial void OnPurchasePriceChanged()
        {
            this.___OnPropertyChanged("PurchasePrice");
        }
        
        partial void OnCurrentValueChanged()
        {
            this.___OnPropertyChanged("CurrentValue");
        }
        
        partial void OnDateCurrentValueEvaluatedChanged()
        {
            this.___OnPropertyChanged("DateCurrentValueEvaluated");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetComments
        {
            get
            {
                return this.AssetComments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetComment> __AssetComments
        {
            get
            {
                if (this.___AssetComments == null)
                {
                    this.___AssetComments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetComment>(
                        this,
                        "AssetComments",
                        () => this._AssetComments,
                        e => global::System.Object.Equals(e.AssetComment_Asset, this.Id));
                }
                return this.___AssetComments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetComment> ___AssetComments;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetMaintenanceActivities
        {
            get
            {
                return this.AssetMaintenanceActivities;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceActivity> __AssetMaintenanceActivities
        {
            get
            {
                if (this.___AssetMaintenanceActivities == null)
                {
                    this.___AssetMaintenanceActivities = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceActivity>(
                        this,
                        "AssetMaintenanceActivities",
                        () => this._AssetMaintenanceActivities,
                        e => global::System.Object.Equals(e.AssetMaintenanceActivity_Asset, this.Id));
                }
                return this.___AssetMaintenanceActivities;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceActivity> ___AssetMaintenanceActivities;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetMaintenanceSchedules
        {
            get
            {
                return this.AssetMaintenanceSchedules;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule> __AssetMaintenanceSchedules
        {
            get
            {
                if (this.___AssetMaintenanceSchedules == null)
                {
                    this.___AssetMaintenanceSchedules = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule>(
                        this,
                        "AssetMaintenanceSchedules",
                        () => this._AssetMaintenanceSchedules,
                        e => global::System.Object.Equals(e.AssetMaintenanceSchedule_Asset, this.Id));
                }
                return this.___AssetMaintenanceSchedules;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule> ___AssetMaintenanceSchedules;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetManufacturer
        {
            get
            {
                return this.AssetManufacturer;
            }
            set
            {
                this.AssetManufacturer = (global::LightSwitchApplication.Implementation.AssetManufacturer)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetManufacturer> __AssetManufacturer
        {
            get
            {
                if (this.___AssetManufacturer == null)
                {
                    this.___AssetManufacturer = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetManufacturer>(
                        this,
                        "AssetManufacturer",
                        new string[] { "AssetManufacturer_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetManufacturer_Asset),
                        () => this._AssetManufacturer,
                        e => this._AssetManufacturer = e);
                }
                return this.___AssetManufacturer;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetManufacturer> ___AssetManufacturer;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetServiceContracts
        {
            get
            {
                return this.AssetServiceContracts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetServiceContract> __AssetServiceContracts
        {
            get
            {
                if (this.___AssetServiceContracts == null)
                {
                    this.___AssetServiceContracts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetServiceContract>(
                        this,
                        "AssetServiceContracts",
                        () => this._AssetServiceContracts,
                        e => global::System.Object.Equals(e.AssetServiceContract_Asset, this.Id));
                }
                return this.___AssetServiceContracts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetServiceContract> ___AssetServiceContracts;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetSubscribers
        {
            get
            {
                return this.AssetSubscribers;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetSubscriber> __AssetSubscribers
        {
            get
            {
                if (this.___AssetSubscribers == null)
                {
                    this.___AssetSubscribers = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetSubscriber>(
                        this,
                        "AssetSubscribers",
                        () => this._AssetSubscribers,
                        e => global::System.Object.Equals(e.AssetSubscriber_Asset, this.Id));
                }
                return this.___AssetSubscribers;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetSubscriber> ___AssetSubscribers;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetSupplier
        {
            get
            {
                return this.AssetSupplier;
            }
            set
            {
                this.AssetSupplier = (global::LightSwitchApplication.Implementation.AssetSupplier)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetSupplier> __AssetSupplier
        {
            get
            {
                if (this.___AssetSupplier == null)
                {
                    this.___AssetSupplier = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetSupplier>(
                        this,
                        "AssetSupplier",
                        new string[] { "AssetSupplier_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetSupplier_Asset),
                        () => this._AssetSupplier,
                        e => this._AssetSupplier = e);
                }
                return this.___AssetSupplier;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetSupplier> ___AssetSupplier;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Asset.DetailsClass.IImplementation.AssetType
        {
            get
            {
                return this.AssetType;
            }
            set
            {
                this.AssetType = (global::LightSwitchApplication.Implementation.AssetType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetType> __AssetType
        {
            get
            {
                if (this.___AssetType == null)
                {
                    this.___AssetType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetType>(
                        this,
                        "AssetType",
                        new string[] { "AssetType_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetType_Asset),
                        () => this._AssetType,
                        e => this._AssetType = e);
                }
                return this.___AssetType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AssetType> ___AssetType;
        
    }
    #endregion
    
    #region AssetServiceContract
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetServiceContract :
        global::LightSwitchApplication.AssetServiceContract.DetailsClass.IImplementation
    {
        partial void OnAssetServiceContract_AssetChanged()
        {
            this.___OnPropertyChanged("AssetServiceContract_Asset");
            this.___OnPropertyChanged("Asset");
        }
        
        partial void OnAssetServiceContract_ServiceContractChanged()
        {
            this.___OnPropertyChanged("AssetServiceContract_ServiceContract");
            this.___OnPropertyChanged("ServiceContract");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetServiceContract.DetailsClass.IImplementation.Asset
        {
            get
            {
                return this.Asset;
            }
            set
            {
                this.Asset = (global::LightSwitchApplication.Implementation.Asset)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> __Asset
        {
            get
            {
                if (this.___Asset == null)
                {
                    this.___Asset = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Asset",
                        new string[] { "AssetServiceContract_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetServiceContract_Asset),
                        () => this._Asset,
                        e => this._Asset = e);
                }
                return this.___Asset;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> ___Asset;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetServiceContract.DetailsClass.IImplementation.ServiceContract
        {
            get
            {
                return this.ServiceContract;
            }
            set
            {
                this.ServiceContract = (global::LightSwitchApplication.Implementation.ServiceContract)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServiceContract> __ServiceContract
        {
            get
            {
                if (this.___ServiceContract == null)
                {
                    this.___ServiceContract = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServiceContract>(
                        this,
                        "ServiceContract",
                        new string[] { "AssetServiceContract_ServiceContract" },
                        e => global::System.Object.Equals(e.Id, this.AssetServiceContract_ServiceContract),
                        () => this._ServiceContract,
                        e => this._ServiceContract = e);
                }
                return this.___ServiceContract;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServiceContract> ___ServiceContract;
        
    }
    #endregion
    
    #region AssetSubscriber
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetSubscriber :
        global::LightSwitchApplication.AssetSubscriber.DetailsClass.IImplementation
    {
        partial void OnAssetSubscriber_AssetChanged()
        {
            this.___OnPropertyChanged("AssetSubscriber_Asset");
            this.___OnPropertyChanged("Asset");
        }
        
        partial void OnAssetSubscriber_EmployeeChanged()
        {
            this.___OnPropertyChanged("AssetSubscriber_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetSubscriber.DetailsClass.IImplementation.Asset
        {
            get
            {
                return this.Asset;
            }
            set
            {
                this.Asset = (global::LightSwitchApplication.Implementation.Asset)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> __Asset
        {
            get
            {
                if (this.___Asset == null)
                {
                    this.___Asset = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Asset",
                        new string[] { "AssetSubscriber_Asset" },
                        e => global::System.Object.Equals(e.Id, this.AssetSubscriber_Asset),
                        () => this._Asset,
                        e => this._Asset = e);
                }
                return this.___Asset;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Asset> ___Asset;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AssetSubscriber.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "AssetSubscriber_Employee" },
                        e => global::System.Object.Equals(e.Id, this.AssetSubscriber_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
    }
    #endregion
    
    #region AssetSupplier
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetSupplier :
        global::LightSwitchApplication.AssetSupplier.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnSupplierChanged()
        {
            this.___OnPropertyChanged("Supplier");
        }
        
        partial void OnAddressLine1Changed()
        {
            this.___OnPropertyChanged("AddressLine1");
        }
        
        partial void OnAddressLine2Changed()
        {
            this.___OnPropertyChanged("AddressLine2");
        }
        
        partial void OnAddressLine3Changed()
        {
            this.___OnPropertyChanged("AddressLine3");
        }
        
        partial void OnAddressLine4Changed()
        {
            this.___OnPropertyChanged("AddressLine4");
        }
        
        partial void OnAddressLine5Changed()
        {
            this.___OnPropertyChanged("AddressLine5");
        }
        
        partial void OnPostCodeChanged()
        {
            this.___OnPropertyChanged("PostCode");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhone1Changed()
        {
            this.___OnPropertyChanged("Phone1");
        }
        
        partial void OnPhone2Changed()
        {
            this.___OnPropertyChanged("Phone2");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnWebsiteChanged()
        {
            this.___OnPropertyChanged("Website");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AssetSupplier.DetailsClass.IImplementation.Assets
        {
            get
            {
                return this.Assets;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset> __Assets
        {
            get
            {
                if (this.___Assets == null)
                {
                    this.___Assets = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Assets",
                        () => this._Assets,
                        e => global::System.Object.Equals(e.AssetSupplier_Asset, this.Id));
                }
                return this.___Assets;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset> ___Assets;
        
    }
    #endregion
    
    #region AssetType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AssetType :
        global::LightSwitchApplication.AssetType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnAssetTypeDescriptionChanged()
        {
            this.___OnPropertyChanged("AssetTypeDescription");
        }
        
        partial void OnInUseChanged()
        {
            this.___OnPropertyChanged("InUse");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AssetType.DetailsClass.IImplementation.Asset
        {
            get
            {
                return this.Asset;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset> __Asset
        {
            get
            {
                if (this.___Asset == null)
                {
                    this.___Asset = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset>(
                        this,
                        "Asset",
                        () => this._Asset,
                        e => global::System.Object.Equals(e.AssetType_Asset, this.Id));
                }
                return this.___Asset;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Asset> ___Asset;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.AssetSubscribers
        {
            get
            {
                return this.AssetSubscribers;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetSubscriber> __AssetSubscribers
        {
            get
            {
                if (this.___AssetSubscribers == null)
                {
                    this.___AssetSubscribers = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetSubscriber>(
                        this,
                        "AssetSubscribers",
                        () => this._AssetSubscribers,
                        e => global::System.Object.Equals(e.AssetSubscriber_Employee, this.Id));
                }
                return this.___AssetSubscribers;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetSubscriber> ___AssetSubscribers;
        
    }
    #endregion
    
    #region ServiceContract
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ServiceContract :
        global::LightSwitchApplication.ServiceContract.DetailsClass.IImplementation
    {
        partial void OnServiceContract_ServiceContractSupplierChanged()
        {
            this.___OnPropertyChanged("ServiceContract_ServiceContractSupplier");
            this.___OnPropertyChanged("ServiceContractSupplier");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnContractReferenceChanged()
        {
            this.___OnPropertyChanged("ContractReference");
        }
        
        partial void OnContractNameChanged()
        {
            this.___OnPropertyChanged("ContractName");
        }
        
        partial void OnContractDescriptionChanged()
        {
            this.___OnPropertyChanged("ContractDescription");
        }
        
        partial void OnStartDateChanged()
        {
            this.___OnPropertyChanged("StartDate");
        }
        
        partial void OnEndDateChanged()
        {
            this.___OnPropertyChanged("EndDate");
        }
        
        partial void OnContractPriceChanged()
        {
            this.___OnPropertyChanged("ContractPrice");
        }
        
        partial void OnCurrentContractChanged()
        {
            this.___OnPropertyChanged("CurrentContract");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ServiceContract.DetailsClass.IImplementation.AssetServiceContracts
        {
            get
            {
                return this.AssetServiceContracts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetServiceContract> __AssetServiceContracts
        {
            get
            {
                if (this.___AssetServiceContracts == null)
                {
                    this.___AssetServiceContracts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetServiceContract>(
                        this,
                        "AssetServiceContracts",
                        () => this._AssetServiceContracts,
                        e => global::System.Object.Equals(e.AssetServiceContract_ServiceContract, this.Id));
                }
                return this.___AssetServiceContracts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AssetServiceContract> ___AssetServiceContracts;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ServiceContract.DetailsClass.IImplementation.ServiceContractSupplier
        {
            get
            {
                return this.ServiceContractSupplier;
            }
            set
            {
                this.ServiceContractSupplier = (global::LightSwitchApplication.Implementation.ServiceContractSupplier)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServiceContractSupplier> __ServiceContractSupplier
        {
            get
            {
                if (this.___ServiceContractSupplier == null)
                {
                    this.___ServiceContractSupplier = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServiceContractSupplier>(
                        this,
                        "ServiceContractSupplier",
                        new string[] { "ServiceContract_ServiceContractSupplier" },
                        e => global::System.Object.Equals(e.Id, this.ServiceContract_ServiceContractSupplier),
                        () => this._ServiceContractSupplier,
                        e => this._ServiceContractSupplier = e);
                }
                return this.___ServiceContractSupplier;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ServiceContractSupplier> ___ServiceContractSupplier;
        
    }
    #endregion
    
    #region ServiceContractSupplier
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ServiceContractSupplier :
        global::LightSwitchApplication.ServiceContractSupplier.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnServiceContractSupplierDetailsChanged()
        {
            this.___OnPropertyChanged("ServiceContractSupplierDetails");
        }
        
        partial void OnContactChanged()
        {
            this.___OnPropertyChanged("Contact");
        }
        
        partial void OnContactJobDescriptionChanged()
        {
            this.___OnPropertyChanged("ContactJobDescription");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhone1Changed()
        {
            this.___OnPropertyChanged("Phone1");
        }
        
        partial void OnPhone2Changed()
        {
            this.___OnPropertyChanged("Phone2");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnWebsiteChanged()
        {
            this.___OnPropertyChanged("Website");
        }
        
        partial void OnAddressLine1Changed()
        {
            this.___OnPropertyChanged("AddressLine1");
        }
        
        partial void OnAddressLine2Changed()
        {
            this.___OnPropertyChanged("AddressLine2");
        }
        
        partial void OnAddressLine3Changed()
        {
            this.___OnPropertyChanged("AddressLine3");
        }
        
        partial void OnAddressLine4Changed()
        {
            this.___OnPropertyChanged("AddressLine4");
        }
        
        partial void OnAddressLine5Changed()
        {
            this.___OnPropertyChanged("AddressLine5");
        }
        
        partial void OnPostCodeChanged()
        {
            this.___OnPropertyChanged("PostCode");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ServiceContractSupplier.DetailsClass.IImplementation.ServiceContracts
        {
            get
            {
                return this.ServiceContracts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ServiceContract> __ServiceContracts
        {
            get
            {
                if (this.___ServiceContracts == null)
                {
                    this.___ServiceContracts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ServiceContract>(
                        this,
                        "ServiceContracts",
                        () => this._ServiceContracts,
                        e => global::System.Object.Equals(e.ServiceContract_ServiceContractSupplier, this.Id));
                }
                return this.___ServiceContracts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ServiceContract> ___ServiceContracts;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetComment))
            {
                return new global::LightSwitchApplication.Implementation.AssetComment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetMaintenanceActivity))
            {
                return new global::LightSwitchApplication.Implementation.AssetMaintenanceActivity();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetMaintenanceSchedule))
            {
                return new global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetMaintenanceType))
            {
                return new global::LightSwitchApplication.Implementation.AssetMaintenanceType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetManufacturer))
            {
                return new global::LightSwitchApplication.Implementation.AssetManufacturer();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Asset))
            {
                return new global::LightSwitchApplication.Implementation.Asset();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetServiceContract))
            {
                return new global::LightSwitchApplication.Implementation.AssetServiceContract();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetSubscriber))
            {
                return new global::LightSwitchApplication.Implementation.AssetSubscriber();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetSupplier))
            {
                return new global::LightSwitchApplication.Implementation.AssetSupplier();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AssetType))
            {
                return new global::LightSwitchApplication.Implementation.AssetType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ServiceContract))
            {
                return new global::LightSwitchApplication.Implementation.ServiceContract();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ServiceContractSupplier))
            {
                return new global::LightSwitchApplication.Implementation.ServiceContractSupplier();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AssetComment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetComment);
            }
            if (typeof(global::LightSwitchApplication.AssetMaintenanceActivity) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetMaintenanceActivity);
            }
            if (typeof(global::LightSwitchApplication.AssetMaintenanceSchedule) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetMaintenanceSchedule);
            }
            if (typeof(global::LightSwitchApplication.AssetMaintenanceType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetMaintenanceType);
            }
            if (typeof(global::LightSwitchApplication.AssetManufacturer) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetManufacturer);
            }
            if (typeof(global::LightSwitchApplication.Asset) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Asset);
            }
            if (typeof(global::LightSwitchApplication.AssetServiceContract) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetServiceContract);
            }
            if (typeof(global::LightSwitchApplication.AssetSubscriber) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetSubscriber);
            }
            if (typeof(global::LightSwitchApplication.AssetSupplier) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetSupplier);
            }
            if (typeof(global::LightSwitchApplication.AssetType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AssetType);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.ServiceContract) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ServiceContract);
            }
            if (typeof(global::LightSwitchApplication.ServiceContractSupplier) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ServiceContractSupplier);
            }
            return null;
        }
    }
}
