

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class AssetMaintenanceSchedule : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the AssetMaintenanceSchedule entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AssetMaintenanceSchedule()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AssetMaintenanceSchedule(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AssetMaintenanceSchedule> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssetMaintenanceSchedule_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssetMaintenanceSchedule_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.SetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MaintenanceTypeIntervalInMonths
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.MaintenanceTypeIntervalInMonths);
            }
            set
            {
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.SetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.MaintenanceTypeIntervalInMonths, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MaintenanceTypeIntervalInMonths_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MaintenanceTypeIntervalInMonths_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MaintenanceTypeIntervalInMonths_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.SetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Asset Asset
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Asset);
            }
            set
            {
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.SetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Asset, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Asset_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Asset_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Asset_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.AssetMaintenanceType AssetMaintenanceType
        {
            get
            {
                return global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.GetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.AssetMaintenanceType);
            }
            set
            {
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.SetValue(this, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.AssetMaintenanceType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssetMaintenanceType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssetMaintenanceType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssetMaintenanceType_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.AssetMaintenanceSchedule,
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass,
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.IImplementation,
                global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass>.Entry
                __AssetMaintenanceScheduleEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass>.Entry(
                    global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.__AssetMaintenanceSchedule_CreateNew,
                    global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.__AssetMaintenanceSchedule_Created,
                    global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.__AssetMaintenanceSchedule_AllowSaveWithErrors);
            private static global::LightSwitchApplication.AssetMaintenanceSchedule __AssetMaintenanceSchedule_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AssetMaintenanceSchedule> es)
            {
                return new global::LightSwitchApplication.AssetMaintenanceSchedule(es);
            }
            private static void __AssetMaintenanceSchedule_Created(global::LightSwitchApplication.AssetMaintenanceSchedule e)
            {
                e.AssetMaintenanceSchedule_Created();
            }
            private static bool __AssetMaintenanceSchedule_AllowSaveWithErrors(global::LightSwitchApplication.AssetMaintenanceSchedule e)
            {
                bool result = false;
                e.AssetMaintenanceSchedule_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int> MaintenanceTypeIntervalInMonths
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.MaintenanceTypeIntervalInMonths) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.Asset> Asset
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Asset) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.Asset>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.AssetMaintenanceType> AssetMaintenanceType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.AssetMaintenanceType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.AssetMaintenanceType>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int MaintenanceTypeIntervalInMonths { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Asset { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation AssetMaintenanceType { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Entry
                    MaintenanceTypeIntervalInMonths = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Entry(
                        "MaintenanceTypeIntervalInMonths",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._MaintenanceTypeIntervalInMonths_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._MaintenanceTypeIntervalInMonths_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._MaintenanceTypeIntervalInMonths_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._MaintenanceTypeIntervalInMonths_GetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._MaintenanceTypeIntervalInMonths_SetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._MaintenanceTypeIntervalInMonths_OnValueChanged);
                private static void _MaintenanceTypeIntervalInMonths_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._MaintenanceTypeIntervalInMonths, sf);
                }
                private static bool _MaintenanceTypeIntervalInMonths_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.MaintenanceTypeIntervalInMonths_IsReadOnly(ref result);
                    return result;
                }
                private static void _MaintenanceTypeIntervalInMonths_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MaintenanceTypeIntervalInMonths_Validate(r);
                }
                private static int _MaintenanceTypeIntervalInMonths_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.MaintenanceTypeIntervalInMonths;
                }
                private static void _MaintenanceTypeIntervalInMonths_SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, int v)
                {
                    d.ImplementationEntity.MaintenanceTypeIntervalInMonths = v;
                }
                private static void _MaintenanceTypeIntervalInMonths_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.MaintenanceTypeIntervalInMonths_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.Asset>.Entry
                    Asset = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.Asset>.Entry(
                        "Asset",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_GetCoreImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_GetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_SetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_Refresh,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._Asset_OnValueChanged);
                private static void _Asset_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.Asset>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Asset, sf);
                }
                private static bool _Asset_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.Asset_IsReadOnly(ref result);
                    return result;
                }
                private static void _Asset_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Asset_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Asset_GetCoreImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Asset;
                }
                private static global::LightSwitchApplication.Asset _Asset_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Asset, global::LightSwitchApplication.Asset.DetailsClass>(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Asset, ref d._Asset);
                }
                private static void _Asset_SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, global::LightSwitchApplication.Asset v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Asset, ref d._Asset, (i, ev) => i.Asset = ev, v);
                }
                private static void _Asset_Refresh(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.Asset, ref d._Asset);
                }
                private static void _Asset_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.Asset_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.AssetMaintenanceType>.Entry
                    AssetMaintenanceType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.AssetMaintenanceType>.Entry(
                        "AssetMaintenanceType",
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_Stub,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_ComputeIsReadOnly,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_Validate,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_GetCoreImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_GetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_SetImplementationValue,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_Refresh,
                        global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties._AssetMaintenanceType_OnValueChanged);
                private static void _AssetMaintenanceType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.AssetMaintenanceType>.Data> c, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, object sf)
                {
                    c(d, ref d._AssetMaintenanceType, sf);
                }
                private static bool _AssetMaintenanceType_ComputeIsReadOnly(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    bool result = false;
                    e.AssetMaintenanceType_IsReadOnly(ref result);
                    return result;
                }
                private static void _AssetMaintenanceType_Validate(global::LightSwitchApplication.AssetMaintenanceSchedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AssetMaintenanceType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _AssetMaintenanceType_GetCoreImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.ImplementationEntity.AssetMaintenanceType;
                }
                private static global::LightSwitchApplication.AssetMaintenanceType _AssetMaintenanceType_GetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.AssetMaintenanceType, global::LightSwitchApplication.AssetMaintenanceType.DetailsClass>(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.AssetMaintenanceType, ref d._AssetMaintenanceType);
                }
                private static void _AssetMaintenanceType_SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d, global::LightSwitchApplication.AssetMaintenanceType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.AssetMaintenanceType, ref d._AssetMaintenanceType, (i, ev) => i.AssetMaintenanceType = ev, v);
                }
                private static void _AssetMaintenanceType_Refresh(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass.PropertySetProperties.AssetMaintenanceType, ref d._AssetMaintenanceType);
                }
                private static void _AssetMaintenanceType_OnValueChanged(global::LightSwitchApplication.AssetMaintenanceSchedule e)
                {
                    e.AssetMaintenanceType_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, int>.Data _MaintenanceTypeIntervalInMonths;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.Asset>.Data _Asset;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AssetMaintenanceSchedule, global::LightSwitchApplication.AssetMaintenanceSchedule.DetailsClass, global::LightSwitchApplication.AssetMaintenanceType>.Data _AssetMaintenanceType;
            
        }
    
        #endregion
    }
    
    #endregion
}
